package body System.wmain is
   pragma Suppress (All_Checks);

   --  main generated by gnatbind
   function main (argc : Integer; argv : Address; envp : Address)
      return Integer;
   pragma Import (C, main);

   --  implementation

   function wmain (argc : Integer; argv : Address; envp : Address)
      return Integer is
   begin
      wargc := argc;
      wargv := argv;
      wenvp := envp;
      return main (0, Null_Address, Null_Address);
   end wmain;

end System.wmain;
