with Ada;
procedure image is
	type Short_Fixed is delta 0.1 digits 2;
	type Long_Fixed is delta 0.1 digits 10;
	type Enum8 is (AAA, BBB, CCC);
	type Enum16 is (AAA, BBB, CCC);
	for Enum16 use (AAA => 0, BBB => 1, CCC => 16#ffff#);
	type Enum32 is (AAA, BBB, CCC);
	for Enum32 use (AAA => 0, BBB => 1, CCC => 16#ffffffff#);
	type Unsigned is mod 2 ** 8;
	type Long_Long_Unsigned is mod 2 ** Long_Long_Integer'Size;
	function Image (X : Boolean) return String renames Boolean'Image;
	function Image (X : Enum8) return String renames Enum8'Image;
	function Image (X : Enum16) return String renames Enum16'Image;
	function Image (X : Enum32) return String renames Enum32'Image;
begin
	Ada.Debug.Put (Boolean'Image (Boolean'First));
	Ada.Debug.Put (Image (Boolean'Last));
	Ada.Debug.Put (Enum8'Image (Enum8'First));
	Ada.Debug.Put (Image (Enum8'Last));
	Ada.Debug.Put (Enum16'Image (Enum16'First));
	Ada.Debug.Put (Image (Enum16'Last));
	Ada.Debug.Put (Enum32'Image (Enum32'First));
	Ada.Debug.Put (Image (Enum32'Last));
	Ada.Debug.Put (Character'Image (Character'First));
	Ada.Debug.Put (Character'Image (Character'Last));
	Ada.Debug.Put (Wide_Character'Image (Wide_Character'First));
	Ada.Debug.Put (Wide_Character'Image (Wide_Character'Last));
	-- when using Wide_Wide_Character'Image, gcc-4.4.*/4.5.* are very slow...???
--	Ada.Debug.Put (Wide_Wide_Character'Image (Wide_Wide_Character'First));
--	Ada.Debug.Put (Wide_Wide_Character'Image (Wide_Wide_Character'Last));
	Ada.Debug.Put (Integer'Image (Integer'First));
	Ada.Debug.Put (Integer'Image (Integer'Last));
	Ada.Debug.Put (Long_Long_Integer'Image (Long_Long_Integer'First));
	Ada.Debug.Put (Long_Long_Integer'Image (Long_Long_Integer'Last));
	Ada.Debug.Put (Unsigned'Image (Unsigned'First));
	Ada.Debug.Put (Unsigned'Image (Unsigned'Last));
	Ada.Debug.Put (Long_Long_Unsigned'Image (Long_Long_Unsigned'First));
	Ada.Debug.Put (Long_Long_Unsigned'Image (Long_Long_Unsigned'Last));
	Ada.Debug.Put (Float'Image (Float'First));
	Ada.Debug.Put (Float'Image (Float'Last));
	Ada.Debug.Put (Long_Float'Image (Long_Float'First));
	Ada.Debug.Put (Long_Float'Image (Long_Float'Last));
	Ada.Debug.Put (Long_Long_Float'Image (Long_Long_Float'First));
	Ada.Debug.Put (Long_Long_Float'Image (Long_Long_Float'Last));
	Ada.Debug.Put (Short_Fixed'Image (Short_Fixed'First));
	Ada.Debug.Put (Short_Fixed'Image (Short_Fixed'Last));
	Ada.Debug.Put (Long_Fixed'Image (Long_Fixed'First));
	Ada.Debug.Put (Long_Fixed'Image (Long_Fixed'Last));
end image;
