pragma License (Unrestricted);
--  runtime unit
with Ada.Exceptions;
package System.Finally is
   --  This unit will be linked if these subprograms are called from
   --    UNIT__finalize_spec, UNIT__finalize_body, or finalize_library
   --    generated by gnatbind.
   pragma Preelaborate;

   --  implementation of Save_Library_Occurrence (s-soflin.ads)
   procedure Save_Library_Occurrence (
      E : Ada.Exceptions.Exception_Occurrence_Access)
      with Export,
         Convention => Ada,
         External_Name => "system__soft_links__save_library_occurrence";

   --  implementation of Reraise_Library_Exception_If_Any (a-except-2005.adb)
   procedure Reraise_Library_Exception_If_Any
      with Export,
         Convention => Ada,
         External_Name => "__gnat_reraise_library_exception_if_any";

end System.Finally;
